language: java
jdk:
  -  openjdk8

branches:
  only:
    - master

# Travis Ci 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r cheol-springboot-webservice *
  - mkdir -p deploy
  - mv cheol-springboot-webservice.zip deploy/cheol-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cheol-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근
    local_dir: deploy
    wait-until-deployed : true

before_install:
  - chmod +x gradlew

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - a7557z@gmail.com
      - a7557z@naver.com