language: java
jdk:
  -  openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis Ci 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r cheol-springboot-webservice *
  - mkdir -p deploy
  - mv cheol-springboot-webservice.zip deploy/cheol-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: cheol-springboot-build # s3버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip파일 접근
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed : true

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - a7557z@gmail.com
      - a7557z@naver.com